packages:
  - "apps/*"
  - "packages/*"
  - "!apps/terminal/frontend"
  - "!apps/browser/frontend"
allowBuilds:
  "@google/genai": true
  "@mongodb-js/zstd": true
  "@swc/core": true
  cbor-extract: true
  esbuild: true
  node-liblzma: true
  protobufjs: true
  sharp: true
minimumReleaseAgeExclude:
  - files-sdk@2.1.0
  - '@fumadocs/base-ui@16.11.1'
  - '@fumadocs/tailwind@0.1.0'
  - fumadocs-core@16.11.1
  - fumadocs-mdx@15.1.0
