/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * skills.sh API
 * Hand-authored spec for the official skills.sh API (https://skills.sh/docs/api). Vercel does not publish a machine-readable OpenAPI/Swagger document for this API, so this file mirrors the documented REST reference and is kept in sync manually. See the `packages/skills-sdk:sync-openapi-spec` skill for the re-sync procedure.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


/**
 * Cache-Control caches this response for roughly 30-60 seconds. Authenticated requests are rate-limited to 600/min per (team, project); see the X-RateLimit-* response headers.
 * @summary Paginated leaderboard of all skills.
 */
export const listSkillsQueryPageDefault = 0;
export const listSkillsQueryPerPageDefault = 100;
export const listSkillsQueryPerPageMax = 500;



export const ListSkillsQueryParams = zod.object({
  "view": zod.enum(['all-time', 'trending', 'hot']).optional().describe('Leaderboard ordering. \"all-time\" ranks by total installs, \"trending\" surfaces recent growth, and \"hot\" ranks by installs in the last 24 hours (adds installsYesterday\/change to each result).'),
  "page": zod.number().default(listSkillsQueryPageDefault).describe('0-indexed page number.'),
  "per_page": zod.number().min(1).max(listSkillsQueryPerPageMax).default(listSkillsQueryPerPageDefault).describe('Number of results to return per page.')
})

export const ListSkillsResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().describe('Stable unique identifier. Format \"{source}\/{slug}\". Pass this verbatim as the `id` path parameter to the detail and audit endpoints.'),
  "slug": zod.string().describe('Skill slug, unique within its source.'),
  "name": zod.string().describe('Human-readable skill name.'),
  "source": zod.string().describe('GitHub \"owner\/repo\" or well-known \"domain.com\" this skill was published from.'),
  "installs": zod.number().describe('Total install count.'),
  "sourceType": zod.enum(['github', 'well-known']).describe('\"github\" for skills hosted in a GitHub repository, \"well-known\" for skills published via a domain\'s .well-known directory.'),
  "installUrl": zod.string().nullable().describe('Installable via `npx skills add {installUrl}`. Null when the skill has no direct install target.'),
  "url": zod.string().describe('Canonical skills.sh page for this skill.'),
  "isDuplicate": zod.boolean().optional().describe('True when this entry duplicates another skill\'s content. Omitted (not false) when not a duplicate — filter these out to show only original skills.'),
  "installsYesterday": zod.number().optional().describe('Installs in the last 24 hours. Only present when view=hot.'),
  "change": zod.number().optional().describe('Day-over-day change in installs. Only present when view=hot.')
}).describe('Summary shape used in listing, search, and curated responses.')),
  "pagination": zod.object({
  "page": zod.number().describe('0-indexed current page.'),
  "perPage": zod.number().describe('Results per page, as requested (or its default\/clamped value).'),
  "total": zod.number().describe('Total number of matching skills across all pages.'),
  "hasMore": zod.boolean().describe('True when a subsequent page exists.')
})
})


/**
 * Single-word queries use fuzzy matching; multi-word queries use semantic search (see searchType in the response). Cache-Control caches this response for roughly 30-60 seconds. Authenticated requests are rate-limited to 600/min per (team, project).
 * @summary Search skills by name or description.
 */
export const searchSkillsQueryQMin = 2;

export const searchSkillsQueryLimitDefault = 50;
export const searchSkillsQueryLimitMax = 200;



export const SearchSkillsQueryParams = zod.object({
  "q": zod.string().min(searchSkillsQueryQMin).describe('Search query. Minimum 2 characters. Single words use fuzzy matching; multi-word queries use semantic search.'),
  "limit": zod.number().min(1).max(searchSkillsQueryLimitMax).default(searchSkillsQueryLimitDefault).describe('Maximum number of results to return.'),
  "owner": zod.string().optional().describe('GitHub owner to search within. Includes skills across all of its repositories.')
})

export const SearchSkillsResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().describe('Stable unique identifier. Format \"{source}\/{slug}\". Pass this verbatim as the `id` path parameter to the detail and audit endpoints.'),
  "slug": zod.string().describe('Skill slug, unique within its source.'),
  "name": zod.string().describe('Human-readable skill name.'),
  "source": zod.string().describe('GitHub \"owner\/repo\" or well-known \"domain.com\" this skill was published from.'),
  "installs": zod.number().describe('Total install count.'),
  "sourceType": zod.enum(['github', 'well-known']).describe('\"github\" for skills hosted in a GitHub repository, \"well-known\" for skills published via a domain\'s .well-known directory.'),
  "installUrl": zod.string().nullable().describe('Installable via `npx skills add {installUrl}`. Null when the skill has no direct install target.'),
  "url": zod.string().describe('Canonical skills.sh page for this skill.'),
  "isDuplicate": zod.boolean().optional().describe('True when this entry duplicates another skill\'s content. Omitted (not false) when not a duplicate — filter these out to show only original skills.'),
  "installsYesterday": zod.number().optional().describe('Installs in the last 24 hours. Only present when view=hot.'),
  "change": zod.number().optional().describe('Day-over-day change in installs. Only present when view=hot.')
}).describe('Summary shape used in listing, search, and curated responses.')),
  "query": zod.string().describe('Echoes the `q` query parameter.'),
  "searchType": zod.enum(['fuzzy', 'semantic']).describe('\"fuzzy\" for single-word queries matched by name\/source, \"semantic\" for multi-word queries matched by meaning.'),
  "count": zod.number().describe('Number of results in `data`.'),
  "durationMs": zod.number().describe('Server-side search time in milliseconds.')
})


/**
 * Grouped by owner. Cache-Control caches this response for roughly 5 minutes. Authenticated requests are rate-limited to 600/min per (team, project).
 * @summary The official curated set of first-party skills.
 */
export const GetCuratedSkillsResponse = zod.object({
  "data": zod.array(zod.object({
  "owner": zod.string().describe('GitHub owner (organization or user) this group belongs to.'),
  "totalInstalls": zod.number().describe('Sum of installs across all of this owner\'s curated skills.'),
  "featuredRepo": zod.string().describe('The owner\'s most prominent repository in this curated set.'),
  "featuredSkill": zod.string().describe('The owner\'s most prominent skill slug in this curated set.'),
  "skills": zod.array(zod.object({
  "id": zod.string().describe('Stable unique identifier. Format \"{source}\/{slug}\". Pass this verbatim as the `id` path parameter to the detail and audit endpoints.'),
  "slug": zod.string().describe('Skill slug, unique within its source.'),
  "name": zod.string().describe('Human-readable skill name.'),
  "source": zod.string().describe('GitHub \"owner\/repo\" or well-known \"domain.com\" this skill was published from.'),
  "installs": zod.number().describe('Total install count.'),
  "sourceType": zod.enum(['github', 'well-known']).describe('\"github\" for skills hosted in a GitHub repository, \"well-known\" for skills published via a domain\'s .well-known directory.'),
  "installUrl": zod.string().nullable().describe('Installable via `npx skills add {installUrl}`. Null when the skill has no direct install target.'),
  "url": zod.string().describe('Canonical skills.sh page for this skill.'),
  "isDuplicate": zod.boolean().optional().describe('True when this entry duplicates another skill\'s content. Omitted (not false) when not a duplicate — filter these out to show only original skills.'),
  "installsYesterday": zod.number().optional().describe('Installs in the last 24 hours. Only present when view=hot.'),
  "change": zod.number().optional().describe('Day-over-day change in installs. Only present when view=hot.')
}).describe('Summary shape used in listing, search, and curated responses.'))
}).describe('One owner\'s curated skills, with aggregate stats.')),
  "totalOwners": zod.number().describe('Number of curated owner groups in `data`.'),
  "totalSkills": zod.number().describe('Total number of curated skills across all groups.'),
  "generatedAt": zod.iso.datetime({"offset":true}).describe('When this curated snapshot was generated.')
})


/**
 * Use the id field from any listing, search, or curated response to construct this path — it is the full "{source}/{slug}" string and may itself contain slashes, so treat it as one opaque path segment rather than two. Cache-Control caches this response for roughly 5 minutes. Authenticated requests are rate-limited to 600/min per (team, project).
 * @summary Detailed information about a single skill.
 */
export const GetSkillParams = zod.object({
  "id": zod.string().describe('\"{source}\/{slug}\", e.g. \"vercel-labs\/skills\/find-skills\" (GitHub) or \"mintlify.com\/mintlify\" (well-known). May contain slashes.')
})

export const GetSkillResponse = zod.object({
  "id": zod.string().describe('Stable unique identifier. Format \"{source}\/{slug}\".'),
  "source": zod.string().describe('GitHub \"owner\/repo\" or well-known \"domain.com\" this skill was published from.'),
  "slug": zod.string().describe('Skill slug, unique within its source.'),
  "installs": zod.number().describe('Total install count.'),
  "hash": zod.string().nullable().describe('SHA-256 hex digest of the concatenated file contents. Null if not yet computed.'),
  "files": zod.array(zod.object({
  "path": zod.string().describe('File path relative to the skill\'s root directory.'),
  "contents": zod.string().describe('Raw file contents.')
}).describe('One file belonging to a skill (SKILL.md or a supporting file).')).nullable().describe('SKILL.md plus any supporting files. Null if the skill\'s content could not be fetched.')
})


/**
 * Aggregates findings from partner scanners (Gen Agent Trust Hub, Socket, Snyk, Runlayer, ZeroLeaks). Returns 404 if no audits exist yet for the given skill. Authenticated requests are rate-limited to 600/min per (team, project).
 * @summary Security audit results for a skill.
 */
export const GetSkillAuditParams = zod.object({
  "id": zod.string().describe('\"{source}\/{slug}\", e.g. \"vercel-labs\/skills\/find-skills\" (GitHub) or \"mintlify.com\/mintlify\" (well-known). May contain slashes.')
})

export const GetSkillAuditResponse = zod.object({
  "id": zod.string().describe('Stable unique identifier. Format \"{source}\/{slug}\".'),
  "source": zod.string().describe('GitHub \"owner\/repo\" or well-known \"domain.com\" this skill was published from.'),
  "slug": zod.string().describe('Skill slug, unique within its source.'),
  "audits": zod.array(zod.object({
  "provider": zod.string().describe('Audit partner display name, e.g. \"Gen Agent Trust Hub\", \"Socket\", \"Snyk\", \"Runlayer\", \"ZeroLeaks\".'),
  "slug": zod.string().describe('Machine-readable partner identifier.'),
  "status": zod.enum(['pass', 'warn', 'fail']).describe('Overall verdict from this audit partner.'),
  "summary": zod.string().describe('One-line human-readable finding.'),
  "auditedAt": zod.iso.datetime({"offset":true}).describe('When this partner last audited the skill.'),
  "riskLevel": zod.enum(['NONE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL']).optional().describe('Severity of the highest-risk finding, when applicable.'),
  "categories": zod.array(zod.string()).optional().describe('Detected risk categories, when the partner reports them.')
}).describe('One partner\'s audit result for a skill.')).describe('One entry per partner that has audited this skill.')
})


