/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * skills.sh API
 * Hand-authored spec for the official skills.sh API (https://skills.sh/docs/api). Vercel does not publish a machine-readable OpenAPI/Swagger document for this API, so this file mirrors the documented REST reference and is kept in sync manually. See the `packages/skills-sdk:sync-openapi-spec` skill for the re-sync procedure.
 * OpenAPI spec version: v1
 */
import type { AuditEntryRiskLevel } from './auditEntryRiskLevel.ts';
import type { AuditEntryStatus } from './auditEntryStatus.ts';

/**
 * One partner's audit result for a skill.
 */
export interface AuditEntry {
  /** Audit partner display name, e.g. "Gen Agent Trust Hub", "Socket", "Snyk", "Runlayer", "ZeroLeaks". */
  provider: string;
  /** Machine-readable partner identifier. */
  slug: string;
  status: AuditEntryStatus;
  /** One-line human-readable finding. */
  summary: string;
  /** When this partner last audited the skill. */
  auditedAt: string;
  riskLevel?: AuditEntryRiskLevel;
  /** Detected risk categories, when the partner reports them. */
  categories?: string[];
}
