/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * skills.sh API
 * Hand-authored spec for the official skills.sh API (https://skills.sh/docs/api). Vercel does not publish a machine-readable OpenAPI/Swagger document for this API, so this file mirrors the documented REST reference and is kept in sync manually. See the `packages/skills-sdk:sync-openapi-spec` skill for the re-sync procedure.
 * OpenAPI spec version: v1
 */
import type { AuditEntry } from './auditEntry.ts';

export interface AuditResponse {
  /** Stable unique identifier. Format "{source}/{slug}". */
  id: string;
  /** GitHub "owner/repo" or well-known "domain.com" this skill was published from. */
  source: string;
  /** Skill slug, unique within its source. */
  slug: string;
  /** One entry per partner that has audited this skill. */
  audits: AuditEntry[];
}
