/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * skills.sh API
 * Hand-authored spec for the official skills.sh API (https://skills.sh/docs/api). Vercel does not publish a machine-readable OpenAPI/Swagger document for this API, so this file mirrors the documented REST reference and is kept in sync manually. See the `packages/skills-sdk:sync-openapi-spec` skill for the re-sync procedure.
 * OpenAPI spec version: v1
 */
import type { CuratedGroup } from './curatedGroup.ts';

export interface CuratedResponse {
  data: CuratedGroup[];
  /** Number of curated owner groups in `data`. */
  totalOwners: number;
  /** Total number of curated skills across all groups. */
  totalSkills: number;
  /** When this curated snapshot was generated. */
  generatedAt: string;
}
