/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * skills.sh API
 * Hand-authored spec for the official skills.sh API (https://skills.sh/docs/api). Vercel does not publish a machine-readable OpenAPI/Swagger document for this API, so this file mirrors the documented REST reference and is kept in sync manually. See the `packages/skills-sdk:sync-openapi-spec` skill for the re-sync procedure.
 * OpenAPI spec version: v1
 */
import type { Skill } from './skill.ts';

/**
 * One owner's curated skills, with aggregate stats.
 */
export interface CuratedGroup {
  /** GitHub owner (organization or user) this group belongs to. */
  owner: string;
  /** Sum of installs across all of this owner's curated skills. */
  totalInstalls: number;
  /** The owner's most prominent repository in this curated set. */
  featuredRepo: string;
  /** The owner's most prominent skill slug in this curated set. */
  featuredSkill: string;
  skills: Skill[];
}
