/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * skills.sh API
 * Hand-authored spec for the official skills.sh API (https://skills.sh/docs/api). Vercel does not publish a machine-readable OpenAPI/Swagger document for this API, so this file mirrors the documented REST reference and is kept in sync manually. See the `packages/skills-sdk:sync-openapi-spec` skill for the re-sync procedure.
 * OpenAPI spec version: v1
 */
import type { DetailFile } from './detailFile.ts';

export interface Detail {
  /** Stable unique identifier. Format "{source}/{slug}". */
  id: string;
  /** GitHub "owner/repo" or well-known "domain.com" this skill was published from. */
  source: string;
  /** Skill slug, unique within its source. */
  slug: string;
  /** Total install count. */
  installs: number;
  /**
     * SHA-256 hex digest of the concatenated file contents. Null if not yet computed.
     * @nullable
     */
  hash: string | null;
  /**
     * SKILL.md plus any supporting files. Null if the skill's content could not be fetched.
     * @nullable
     */
  files: DetailFile[] | null;
}
