/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * skills.sh API
 * Hand-authored spec for the official skills.sh API (https://skills.sh/docs/api). Vercel does not publish a machine-readable OpenAPI/Swagger document for this API, so this file mirrors the documented REST reference and is kept in sync manually. See the `packages/skills-sdk:sync-openapi-spec` skill for the re-sync procedure.
 * OpenAPI spec version: v1
 */

/**
 * "all-time" (default) ranks by total installs, "trending" surfaces recent growth, "hot" ranks by installs in the last 24 hours.
 */
export type ListSkillsView = typeof ListSkillsView[keyof typeof ListSkillsView];


export const ListSkillsView = {
  'all-time': 'all-time',
  trending: 'trending',
  hot: 'hot',
} as const;
