/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * skills.sh API
 * Hand-authored spec for the official skills.sh API (https://skills.sh/docs/api). Vercel does not publish a machine-readable OpenAPI/Swagger document for this API, so this file mirrors the documented REST reference and is kept in sync manually. See the `packages/skills-sdk:sync-openapi-spec` skill for the re-sync procedure.
 * OpenAPI spec version: v1
 */
import type { ListSkillsView } from './listSkillsView.ts';

export type ListSkillsParams = {
/**
 * Leaderboard ordering. "all-time" ranks by total installs, "trending" surfaces recent growth, and "hot" ranks by installs in the last 24 hours (adds installsYesterday/change to each result).
 */
view?: ListSkillsView;
/**
 * 0-indexed page number.
 */
page?: number;
/**
 * Number of results to return per page.
 * @minimum 1
 * @maximum 500
 */
per_page?: number;
};
