/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * skills.sh API
 * Hand-authored spec for the official skills.sh API (https://skills.sh/docs/api). Vercel does not publish a machine-readable OpenAPI/Swagger document for this API, so this file mirrors the documented REST reference and is kept in sync manually. See the `packages/skills-sdk:sync-openapi-spec` skill for the re-sync procedure.
 * OpenAPI spec version: v1
 */
import type { SearchResponseSearchType } from './searchResponseSearchType.ts';
import type { Skill } from './skill.ts';

export interface SearchResponse {
  data: Skill[];
  /** Echoes the `q` query parameter. */
  query: string;
  searchType: SearchResponseSearchType;
  /** Number of results in `data`. */
  count: number;
  /** Server-side search time in milliseconds. */
  durationMs: number;
}
