/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * skills.sh API
 * Hand-authored spec for the official skills.sh API (https://skills.sh/docs/api). Vercel does not publish a machine-readable OpenAPI/Swagger document for this API, so this file mirrors the documented REST reference and is kept in sync manually. See the `packages/skills-sdk:sync-openapi-spec` skill for the re-sync procedure.
 * OpenAPI spec version: v1
 */

export type SearchSkillsParams = {
/**
 * Search query. Minimum 2 characters. Single words use fuzzy matching; multi-word queries use semantic search.
 * @minLength 2
 */
q: string;
/**
 * Maximum number of results to return.
 * @minimum 1
 * @maximum 200
 */
limit?: number;
/**
 * GitHub owner to search within. Includes skills across all of its repositories.
 */
owner?: string;
};
