/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * skills.sh API
 * Hand-authored spec for the official skills.sh API (https://skills.sh/docs/api). Vercel does not publish a machine-readable OpenAPI/Swagger document for this API, so this file mirrors the documented REST reference and is kept in sync manually. See the `packages/skills-sdk:sync-openapi-spec` skill for the re-sync procedure.
 * OpenAPI spec version: v1
 */

/**
 * "github" for skills hosted in a GitHub repository, "well-known" for skills published via a domain's .well-known directory.
 */
export type SkillSourceType = typeof SkillSourceType[keyof typeof SkillSourceType];


export const SkillSourceType = {
  github: 'github',
  'well-known': 'well-known',
} as const;
