/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * skills.sh API
 * Hand-authored spec for the official skills.sh API (https://skills.sh/docs/api). Vercel does not publish a machine-readable OpenAPI/Swagger document for this API, so this file mirrors the documented REST reference and is kept in sync manually. See the `packages/skills-sdk:sync-openapi-spec` skill for the re-sync procedure.
 * OpenAPI spec version: v1
 */
import type { SkillSourceType } from './skillSourceType.ts';

/**
 * Summary shape used in listing, search, and curated responses.
 */
export interface Skill {
  /** Stable unique identifier. Format "{source}/{slug}". Pass this verbatim as the `id` path parameter to the detail and audit endpoints. */
  id: string;
  /** Skill slug, unique within its source. */
  slug: string;
  /** Human-readable skill name. */
  name: string;
  /** GitHub "owner/repo" or well-known "domain.com" this skill was published from. */
  source: string;
  /** Total install count. */
  installs: number;
  sourceType: SkillSourceType;
  /**
     * Installable via `npx skills add {installUrl}`. Null when the skill has no direct install target.
     * @nullable
     */
  installUrl: string | null;
  /** Canonical skills.sh page for this skill. */
  url: string;
  /** True when this entry duplicates another skill's content. Omitted (not false) when not a duplicate — filter these out to show only original skills. */
  isDuplicate?: boolean;
  /** Installs in the last 24 hours. Only present when view=hot. */
  installsYesterday?: number;
  /** Day-over-day change in installs. Only present when view=hot. */
  change?: number;
}
