/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * skills.sh API
 * Hand-authored spec for the official skills.sh API (https://skills.sh/docs/api). Vercel does not publish a machine-readable OpenAPI/Swagger document for this API, so this file mirrors the documented REST reference and is kept in sync manually. See the `packages/skills-sdk:sync-openapi-spec` skill for the re-sync procedure.
 * OpenAPI spec version: v1
 */
import type {
  AuditResponse,
  BadRequestResponse,
  CuratedResponse,
  Detail,
  ListResponse,
  ListSkillsParams,
  NotFoundResponse,
  RateLimitedResponse,
  SearchResponse,
  SearchSkillsParams,
  UnauthorizedResponse,
  UnavailableResponse
} from './model';


export type listSkillsResponse200 = {
  data: ListResponse
  status: 200
}

export type listSkillsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type listSkillsResponse429 = {
  data: RateLimitedResponse
  status: 429
}

export type listSkillsResponse503 = {
  data: UnavailableResponse
  status: 503
}

export type listSkillsResponseSuccess = (listSkillsResponse200) & {
  headers: Headers;
};
export type listSkillsResponseError = (listSkillsResponse401 | listSkillsResponse429 | listSkillsResponse503) & {
  headers: Headers;
};

export type listSkillsResponse = (listSkillsResponseSuccess | listSkillsResponseError)

export const getListSkillsUrl = (params?: ListSkillsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://skills.sh/api/v1/skills?${stringifiedParams}` : `https://skills.sh/api/v1/skills`
}

/**
 * Cache-Control caches this response for roughly 30-60 seconds. Authenticated requests are rate-limited to 600/min per (team, project); see the X-RateLimit-* response headers.
 * @summary Paginated leaderboard of all skills.
 */
export const listSkills = async (params?: ListSkillsParams, options?: RequestInit): Promise<listSkillsResponse> => {

  const res = await fetch(getListSkillsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listSkillsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listSkillsResponse
}



export type searchSkillsResponse200 = {
  data: SearchResponse
  status: 200
}

export type searchSkillsResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type searchSkillsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type searchSkillsResponse429 = {
  data: RateLimitedResponse
  status: 429
}

export type searchSkillsResponse503 = {
  data: UnavailableResponse
  status: 503
}

export type searchSkillsResponseSuccess = (searchSkillsResponse200) & {
  headers: Headers;
};
export type searchSkillsResponseError = (searchSkillsResponse400 | searchSkillsResponse401 | searchSkillsResponse429 | searchSkillsResponse503) & {
  headers: Headers;
};

export type searchSkillsResponse = (searchSkillsResponseSuccess | searchSkillsResponseError)

export const getSearchSkillsUrl = (params: SearchSkillsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://skills.sh/api/v1/skills/search?${stringifiedParams}` : `https://skills.sh/api/v1/skills/search`
}

/**
 * Single-word queries use fuzzy matching; multi-word queries use semantic search (see searchType in the response). Cache-Control caches this response for roughly 30-60 seconds. Authenticated requests are rate-limited to 600/min per (team, project).
 * @summary Search skills by name or description.
 */
export const searchSkills = async (params: SearchSkillsParams, options?: RequestInit): Promise<searchSkillsResponse> => {

  const res = await fetch(getSearchSkillsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: searchSkillsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as searchSkillsResponse
}



export type getCuratedSkillsResponse200 = {
  data: CuratedResponse
  status: 200
}

export type getCuratedSkillsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getCuratedSkillsResponse429 = {
  data: RateLimitedResponse
  status: 429
}

export type getCuratedSkillsResponse503 = {
  data: UnavailableResponse
  status: 503
}

export type getCuratedSkillsResponseSuccess = (getCuratedSkillsResponse200) & {
  headers: Headers;
};
export type getCuratedSkillsResponseError = (getCuratedSkillsResponse401 | getCuratedSkillsResponse429 | getCuratedSkillsResponse503) & {
  headers: Headers;
};

export type getCuratedSkillsResponse = (getCuratedSkillsResponseSuccess | getCuratedSkillsResponseError)

export const getGetCuratedSkillsUrl = () => {




  return `https://skills.sh/api/v1/skills/curated`
}

/**
 * Grouped by owner. Cache-Control caches this response for roughly 5 minutes. Authenticated requests are rate-limited to 600/min per (team, project).
 * @summary The official curated set of first-party skills.
 */
export const getCuratedSkills = async ( options?: RequestInit): Promise<getCuratedSkillsResponse> => {

  const res = await fetch(getGetCuratedSkillsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getCuratedSkillsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getCuratedSkillsResponse
}



export type getSkillResponse200 = {
  data: Detail
  status: 200
}

export type getSkillResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getSkillResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getSkillResponse429 = {
  data: RateLimitedResponse
  status: 429
}

export type getSkillResponse503 = {
  data: UnavailableResponse
  status: 503
}

export type getSkillResponseSuccess = (getSkillResponse200) & {
  headers: Headers;
};
export type getSkillResponseError = (getSkillResponse401 | getSkillResponse404 | getSkillResponse429 | getSkillResponse503) & {
  headers: Headers;
};

export type getSkillResponse = (getSkillResponseSuccess | getSkillResponseError)

export const getGetSkillUrl = (id: string,) => {




  return `https://skills.sh/api/v1/skills/${id}`
}

/**
 * Use the id field from any listing, search, or curated response to construct this path — it is the full "{source}/{slug}" string and may itself contain slashes, so treat it as one opaque path segment rather than two. Cache-Control caches this response for roughly 5 minutes. Authenticated requests are rate-limited to 600/min per (team, project).
 * @summary Detailed information about a single skill.
 */
export const getSkill = async (id: string, options?: RequestInit): Promise<getSkillResponse> => {

  const res = await fetch(getGetSkillUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getSkillResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSkillResponse
}



export type getSkillAuditResponse200 = {
  data: AuditResponse
  status: 200
}

export type getSkillAuditResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getSkillAuditResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getSkillAuditResponse429 = {
  data: RateLimitedResponse
  status: 429
}

export type getSkillAuditResponse503 = {
  data: UnavailableResponse
  status: 503
}

export type getSkillAuditResponseSuccess = (getSkillAuditResponse200) & {
  headers: Headers;
};
export type getSkillAuditResponseError = (getSkillAuditResponse401 | getSkillAuditResponse404 | getSkillAuditResponse429 | getSkillAuditResponse503) & {
  headers: Headers;
};

export type getSkillAuditResponse = (getSkillAuditResponseSuccess | getSkillAuditResponseError)

export const getGetSkillAuditUrl = (id: string,) => {




  return `https://skills.sh/api/v1/skills/audit/${id}`
}

/**
 * Aggregates findings from partner scanners (Gen Agent Trust Hub, Socket, Snyk, Runlayer, ZeroLeaks). Returns 404 if no audits exist yet for the given skill. Authenticated requests are rate-limited to 600/min per (team, project).
 * @summary Security audit results for a skill.
 */
export const getSkillAudit = async (id: string, options?: RequestInit): Promise<getSkillAuditResponse> => {

  const res = await fetch(getGetSkillAuditUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getSkillAuditResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSkillAuditResponse
}



