/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * AI Gateway REST API
 * Hand-authored spec for Vercel's AI Gateway REST API (https://vercel.com/docs/ai-gateway/sdks-and-apis/rest-api). Vercel does not publish a machine-readable OpenAPI/Swagger document for this API, so this file mirrors the documented REST reference and is kept in sync manually. See the `packages/ai-gateway-sdk:sync-openapi-spec` skill for the re-sync procedure. This covers only the lookup/discovery endpoints (models, credits, generation, spend reports) — sending inference requests goes through the Chat Completions, Responses, Anthropic Messages, or OpenResponses APIs, which are not modeled here.
 * OpenAPI spec version: v1
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  BadRequestResponse,
  CreditsResponse,
  ForbiddenResponse,
  GetGenerationParams,
  GetGenerationResponse,
  GetModelEndpointsResponse,
  GetSpendReportParams,
  InternalServerErrorResponse,
  ListModelsResponse,
  NotFoundResponse,
  SpendReportResponse,
  UnauthorizedResponse,
  UnavailableResponse
} from './model';






 export type listModelsResponse200 = {
  data: ListModelsResponse
  status: 200
}

export type listModelsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type listModelsResponse503 = {
  data: UnavailableResponse
  status: 503
}

export type listModelsResponseSuccess = (listModelsResponse200) & {
  headers: Headers;
};
export type listModelsResponseError = (listModelsResponse500 | listModelsResponse503) & {
  headers: Headers;
};

export type listModelsResponse = (listModelsResponseSuccess | listModelsResponseError)

export const getListModelsUrl = () => {




  return `https://ai-gateway.vercel.sh/v1/models`
}

/**
 * Follows the OpenAI models API format. No authentication required.
 * @summary List all available models.
 */
export const listModels = async ( options?: RequestInit): Promise<listModelsResponse> => {

  const res = await fetch(getListModelsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listModelsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listModelsResponse
}




export const getListModelsKey = () => [`https://ai-gateway.vercel.sh/v1/models`] as const;

export type ListModelsQueryResult = NonNullable<Awaited<ReturnType<typeof listModels>>>

/**
 * @summary List all available models.
 */
export const useListModels = <TError = Promise<InternalServerErrorResponse | UnavailableResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof listModels>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getListModelsKey() : null);
  const swrFn = () => listModels(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type getModelEndpointsResponse200 = {
  data: GetModelEndpointsResponse
  status: 200
}

export type getModelEndpointsResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getModelEndpointsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getModelEndpointsResponse503 = {
  data: UnavailableResponse
  status: 503
}

export type getModelEndpointsResponseSuccess = (getModelEndpointsResponse200) & {
  headers: Headers;
};
export type getModelEndpointsResponseError = (getModelEndpointsResponse404 | getModelEndpointsResponse500 | getModelEndpointsResponse503) & {
  headers: Headers;
};

export type getModelEndpointsResponse = (getModelEndpointsResponseSuccess | getModelEndpointsResponseError)

export const getGetModelEndpointsUrl = (creator: string,
    model: string,) => {




  return `https://ai-gateway.vercel.sh/v1/models/${creator}/${model}/endpoints`
}

/**
 * Returns per-endpoint pricing, capabilities, uptime, and throughput for every provider serving the given model. No authentication required.
 * @summary Get every provider endpoint serving a model.
 */
export const getModelEndpoints = async (creator: string,
    model: string, options?: RequestInit): Promise<getModelEndpointsResponse> => {

  const res = await fetch(getGetModelEndpointsUrl(creator,model),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getModelEndpointsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getModelEndpointsResponse
}




export const getGetModelEndpointsKey = (creator: string,
    model: string,) => [`https://ai-gateway.vercel.sh/v1/models/${creator}/${model}/endpoints`] as const;

export type GetModelEndpointsQueryResult = NonNullable<Awaited<ReturnType<typeof getModelEndpoints>>>

/**
 * @summary Get every provider endpoint serving a model.
 */
export const useGetModelEndpoints = <TError = Promise<NotFoundResponse | InternalServerErrorResponse | UnavailableResponse>>(
  creator: string,
    model: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getModelEndpoints>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && creator !== null && creator !== undefined && model !== null && model !== undefined
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetModelEndpointsKey(creator,model) : null);
  const swrFn = () => getModelEndpoints(creator,model, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type getCreditsResponse200 = {
  data: CreditsResponse
  status: 200
}

export type getCreditsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getCreditsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getCreditsResponse503 = {
  data: UnavailableResponse
  status: 503
}

export type getCreditsResponseSuccess = (getCreditsResponse200) & {
  headers: Headers;
};
export type getCreditsResponseError = (getCreditsResponse401 | getCreditsResponse500 | getCreditsResponse503) & {
  headers: Headers;
};

export type getCreditsResponse = (getCreditsResponseSuccess | getCreditsResponseError)

export const getGetCreditsUrl = () => {




  return `https://ai-gateway.vercel.sh/v1/credits`
}

/**
 * Returns the team's current AI Gateway Credits balance and lifetime spend. The team is inferred from the API key or Vercel OIDC token.
 * @summary Check the team's AI Gateway Credits balance and total spend.
 */
export const getCredits = async ( options?: RequestInit): Promise<getCreditsResponse> => {

  const res = await fetch(getGetCreditsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getCreditsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getCreditsResponse
}




export const getGetCreditsKey = () => [`https://ai-gateway.vercel.sh/v1/credits`] as const;

export type GetCreditsQueryResult = NonNullable<Awaited<ReturnType<typeof getCredits>>>

/**
 * @summary Check the team's AI Gateway Credits balance and total spend.
 */
export const useGetCredits = <TError = Promise<UnauthorizedResponse | InternalServerErrorResponse | UnavailableResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getCredits>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetCreditsKey() : null);
  const swrFn = () => getCredits(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type getGenerationResponse200 = {
  data: GetGenerationResponse
  status: 200
}

export type getGenerationResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type getGenerationResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getGenerationResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getGenerationResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getGenerationResponse503 = {
  data: UnavailableResponse
  status: 503
}

export type getGenerationResponseSuccess = (getGenerationResponse200) & {
  headers: Headers;
};
export type getGenerationResponseError = (getGenerationResponse400 | getGenerationResponse401 | getGenerationResponse404 | getGenerationResponse500 | getGenerationResponse503) & {
  headers: Headers;
};

export type getGenerationResponse = (getGenerationResponseSuccess | getGenerationResponseError)

export const getGetGenerationUrl = (params: GetGenerationParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://ai-gateway.vercel.sh/v1/generation?${stringifiedParams}` : `https://ai-gateway.vercel.sh/v1/generation`
}

/**
 * Generation information becomes available shortly after the generation completes. Much of this data is also returned in `providerMetadata` on the chat completion response. Generation IDs are returned as the `id` field on every chat completion response, and injected into the first content chunk on streaming responses so you can capture them before the stream completes.
 * @summary Look up cost, latency, and token usage for a specific generation.
 */
export const getGeneration = async (params: GetGenerationParams, options?: RequestInit): Promise<getGenerationResponse> => {

  const res = await fetch(getGetGenerationUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getGenerationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getGenerationResponse
}




export const getGetGenerationKey = (params: GetGenerationParams,) => [`https://ai-gateway.vercel.sh/v1/generation`, ...(params ? [params]: [])] as const;

export type GetGenerationQueryResult = NonNullable<Awaited<ReturnType<typeof getGeneration>>>

/**
 * @summary Look up cost, latency, and token usage for a specific generation.
 */
export const useGetGeneration = <TError = Promise<BadRequestResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse | UnavailableResponse>>(
  params: GetGenerationParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getGeneration>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetGenerationKey(params) : null);
  const swrFn = () => getGeneration(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type getSpendReportResponse200 = {
  data: SpendReportResponse
  status: 200
}

export type getSpendReportResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type getSpendReportResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getSpendReportResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getSpendReportResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getSpendReportResponse503 = {
  data: UnavailableResponse
  status: 503
}

export type getSpendReportResponseSuccess = (getSpendReportResponse200) & {
  headers: Headers;
};
export type getSpendReportResponseError = (getSpendReportResponse400 | getSpendReportResponse401 | getSpendReportResponse403 | getSpendReportResponse500 | getSpendReportResponse503) & {
  headers: Headers;
};

export type getSpendReportResponse = (getSpendReportResponseSuccess | getSpendReportResponseError)

export const getGetSpendReportUrl = (params: GetSpendReportParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://ai-gateway.vercel.sh/v1/report?${stringifiedParams}` : `https://ai-gateway.vercel.sh/v1/report`
}

/**
 * Returns aggregated spend over a date range. The team is inferred from the API key or OIDC token. Available on Pro and Enterprise plans only — Hobby and Pro-trial plans cannot use this endpoint. Custom Reporting is billed per query; see https://vercel.com/docs/ai-gateway/observability-and-spend/custom-reporting for pricing. It can take a few minutes for requests to appear in this endpoint. Each row contains only the single grouping field that matches `group_by`, plus the aggregated metrics.
 * @summary Query aggregated spend reports for the team.
 */
export const getSpendReport = async (params: GetSpendReportParams, options?: RequestInit): Promise<getSpendReportResponse> => {

  const res = await fetch(getGetSpendReportUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getSpendReportResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSpendReportResponse
}




export const getGetSpendReportKey = (params: GetSpendReportParams,) => [`https://ai-gateway.vercel.sh/v1/report`, ...(params ? [params]: [])] as const;

export type GetSpendReportQueryResult = NonNullable<Awaited<ReturnType<typeof getSpendReport>>>

/**
 * @summary Query aggregated spend reports for the team.
 */
export const useGetSpendReport = <TError = Promise<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse | UnavailableResponse>>(
  params: GetSpendReportParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getSpendReport>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetSpendReportKey(params) : null);
  const swrFn = () => getSpendReport(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

