/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * AI Gateway REST API
 * Hand-authored spec for Vercel's AI Gateway REST API (https://vercel.com/docs/ai-gateway/sdks-and-apis/rest-api). Vercel does not publish a machine-readable OpenAPI/Swagger document for this API, so this file mirrors the documented REST reference and is kept in sync manually. See the `packages/ai-gateway-sdk:sync-openapi-spec` skill for the re-sync procedure. This covers only the lookup/discovery endpoints (models, credits, generation, spend reports) — sending inference requests goes through the Chat Completions, Responses, Anthropic Messages, or OpenResponses APIs, which are not modeled here.
 * OpenAPI spec version: v1
 */

export interface Generation {
  /** The generation ID. */
  id: string;
  /** Total cost in USD for this generation, including any surcharges (e.g. Zero Data Retention or Custom Reporting writes). */
  total_cost: number;
  /** Market price the provider would have charged for the inference. Non-zero only for BYOK generations, where total_cost does not include this amount; 0 otherwise. */
  upstream_inference_cost: number;
  /** Same as total_cost. Kept for compatibility with the OpenRouter schema this endpoint mirrors. */
  usage: number;
  /** ISO 8601 timestamp when the generation was created. */
  created_at: string;
  /** Model identifier used for this generation. */
  model: string;
  /** Whether this generation used Bring Your Own Key (BYOK) credentials. */
  is_byok: boolean;
  /** The provider that served this generation. */
  provider_name: string;
  /** Whether this generation used streaming. */
  streamed: boolean;
  /** Why the generation ended, e.g. "stop", "length", "content_filter", "tool_calls". */
  finish_reason: string;
  /** Time to first token in milliseconds. */
  latency: number;
  /** Total generation time in milliseconds. */
  generation_time: number;
  /** Number of prompt tokens. */
  tokens_prompt: number;
  /** Number of completion tokens. */
  tokens_completion: number;
  /** Native prompt tokens (provider-specific). */
  native_tokens_prompt: number;
  /** Native completion tokens (provider-specific). */
  native_tokens_completion: number;
  /** Reasoning tokens used. */
  native_tokens_reasoning: number;
  /** Cached input tokens read. */
  native_tokens_cached: number;
  /** Cache creation tokens written. */
  native_tokens_cache_creation: number;
  /** Number of billable web search calls performed during this generation. */
  billable_web_search_calls: number;
}
