/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * AI Gateway REST API
 * Hand-authored spec for Vercel's AI Gateway REST API (https://vercel.com/docs/ai-gateway/sdks-and-apis/rest-api). Vercel does not publish a machine-readable OpenAPI/Swagger document for this API, so this file mirrors the documented REST reference and is kept in sync manually. See the `packages/ai-gateway-sdk:sync-openapi-spec` skill for the re-sync procedure. This covers only the lookup/discovery endpoints (models, credits, generation, spend reports) — sending inference requests goes through the Chat Completions, Responses, Anthropic Messages, or OpenResponses APIs, which are not modeled here.
 * OpenAPI spec version: v1
 */
import type { SpendReportCredentialType } from './spendReportCredentialType.ts';
import type { SpendReportDatePart } from './spendReportDatePart.ts';
import type { SpendReportGroupBy } from './spendReportGroupBy.ts';
import type { SpendReportTagsMatch } from './spendReportTagsMatch.ts';

export type GetSpendReportParams = {
/**
 * Start date in YYYY-MM-DD format, inclusive, UTC.
 */
start_date: string;
/**
 * End date in YYYY-MM-DD format, inclusive, UTC.
 */
end_date: string;
/**
 * How to aggregate results. Each row represents one bucket of this dimension.
 */
group_by?: SpendReportGroupBy;
/**
 * Time granularity. Only applies when group_by=day. Use "hour" for per-hour rows, "day" for per-day rows.
 */
date_part?: SpendReportDatePart;
/**
 * Filter by a specific user ID.
 */
user_id?: string;
/**
 * Filter by a specific model in creator/model-name format.
 */
model?: string;
/**
 * Filter by provider.
 */
provider?: string;
/**
 * Filter by credential type.
 */
credential_type?: SpendReportCredentialType;
/**
 * Filter to Zero Data Retention (ZDR)-requested vs non-ZDR requests.
 */
zero_data_retention?: boolean;
/**
 * Filter by one or more comma-separated tags. By default, requests match when they contain any listed tag.
 */
tags?: string;
/**
 * Match mode for `tags`. Use "any" to match requests with any listed tag, or "all" to require every listed tag.
 */
tags_match?: SpendReportTagsMatch;
};
