/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * AI Gateway REST API
 * Hand-authored spec for Vercel's AI Gateway REST API (https://vercel.com/docs/ai-gateway/sdks-and-apis/rest-api). Vercel does not publish a machine-readable OpenAPI/Swagger document for this API, so this file mirrors the documented REST reference and is kept in sync manually. See the `packages/ai-gateway-sdk:sync-openapi-spec` skill for the re-sync procedure. This covers only the lookup/discovery endpoints (models, credits, generation, spend reports) — sending inference requests goes through the Chat Completions, Responses, Anthropic Messages, or OpenResponses APIs, which are not modeled here.
 * OpenAPI spec version: v1
 */

export * from './badRequestResponse.ts';
export * from './creditsResponse.ts';
export * from './endpointPricing.ts';
export * from './errorDetail.ts';
export * from './errorResponse.ts';
export * from './forbiddenResponse.ts';
export * from './generation.ts';
export * from './getGenerationParams.ts';
export * from './getGenerationResponse.ts';
export * from './getModelEndpointsResponse.ts';
export * from './getSpendReportParams.ts';
export * from './internalServerErrorResponse.ts';
export * from './listModelsResponse.ts';
export * from './model.ts';
export * from './modelArchitecture.ts';
export * from './modelEndpoint.ts';
export * from './modelEndpointsDetail.ts';
export * from './modelPricing.ts';
export * from './modelType.ts';
export * from './notFoundResponse.ts';
export * from './percentileStats.ts';
export * from './pricingTier.ts';
export * from './spendReportCredentialType.ts';
export * from './spendReportDatePart.ts';
export * from './spendReportGroupBy.ts';
export * from './spendReportResponse.ts';
export * from './spendReportRow.ts';
export * from './spendReportTagsMatch.ts';
export * from './unauthorizedResponse.ts';
export * from './unavailableResponse.ts';
