/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * AI Gateway REST API
 * Hand-authored spec for Vercel's AI Gateway REST API (https://vercel.com/docs/ai-gateway/sdks-and-apis/rest-api). Vercel does not publish a machine-readable OpenAPI/Swagger document for this API, so this file mirrors the documented REST reference and is kept in sync manually. See the `packages/ai-gateway-sdk:sync-openapi-spec` skill for the re-sync procedure. This covers only the lookup/discovery endpoints (models, credits, generation, spend reports) — sending inference requests goes through the Chat Completions, Responses, Anthropic Messages, or OpenResponses APIs, which are not modeled here.
 * OpenAPI spec version: v1
 */
import type { ModelPricing } from './modelPricing.ts';
import type { ModelType } from './modelType.ts';

export interface Model {
  /** Model identifier, e.g. "openai/gpt-5.5". */
  id: string;
  /** Always "model". */
  object: string;
  /** Unix timestamp when the model was added to AI Gateway. */
  created: number;
  /** Unix timestamp when the model was released by its creator. */
  released: number;
  /** Model provider or owner. */
  owned_by: string;
  /** Human-readable model name. */
  name: string;
  /** Model description. */
  description: string;
  /** Maximum context length in tokens. */
  context_window: number;
  /** Maximum output tokens. */
  max_tokens: number;
  type: ModelType;
  /** Capability tags, e.g. "reasoning", "tool-use", "vision", "file-input". */
  tags: string[];
  pricing: ModelPricing;
}
