/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * AI Gateway REST API
 * Hand-authored spec for Vercel's AI Gateway REST API (https://vercel.com/docs/ai-gateway/sdks-and-apis/rest-api). Vercel does not publish a machine-readable OpenAPI/Swagger document for this API, so this file mirrors the documented REST reference and is kept in sync manually. See the `packages/ai-gateway-sdk:sync-openapi-spec` skill for the re-sync procedure. This covers only the lookup/discovery endpoints (models, credits, generation, spend reports) — sending inference requests goes through the Chat Completions, Responses, Anthropic Messages, or OpenResponses APIs, which are not modeled here.
 * OpenAPI spec version: v1
 */
import type { PricingTier } from './pricingTier.ts';

/**
 * Pricing information. Structure varies by model type — most fields are optional and only present for the relevant model type.
 */
export interface ModelPricing {
  /** Base cost per input token. */
  input?: string;
  /** Tiered pricing for input tokens, when applicable. */
  input_tiers?: PricingTier[];
  /** Base cost per output token (language models only). */
  output?: string;
  /** Tiered pricing for output tokens, when applicable. */
  output_tiers?: PricingTier[];
  /** Cost per cached input token (read). */
  input_cache_read?: string;
  /** Cost per input token (cache write). */
  input_cache_write?: string;
  /** Cost per generated image (image models only). */
  image?: string;
  /** Cost per web search request. */
  web_search?: string;
}
