/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * AI Gateway REST API
 * Hand-authored spec for Vercel's AI Gateway REST API (https://vercel.com/docs/ai-gateway/sdks-and-apis/rest-api). Vercel does not publish a machine-readable OpenAPI/Swagger document for this API, so this file mirrors the documented REST reference and is kept in sync manually. See the `packages/ai-gateway-sdk:sync-openapi-spec` skill for the re-sync procedure. This covers only the lookup/discovery endpoints (models, credits, generation, spend reports) — sending inference requests goes through the Chat Completions, Responses, Anthropic Messages, or OpenResponses APIs, which are not modeled here.
 * OpenAPI spec version: v1
 */
import type { EndpointPricing } from './endpointPricing.ts';
import type { PercentileStats } from './percentileStats.ts';

/**
 * One provider's endpoint serving a model.
 */
export interface ModelEndpoint {
  /** Endpoint display name, e.g. "google | google/gemini-3.1-pro-preview". */
  name: string;
  /** Human-readable model name. */
  model_name: string;
  /** Maximum context window in tokens for this endpoint. */
  context_length: number;
  pricing: EndpointPricing;
  /** Provider name, e.g. "google", "anthropic". */
  provider_name: string;
  /** Maximum output tokens for this endpoint. */
  max_completion_tokens: number;
  /** API parameters supported by this endpoint, e.g. "max_tokens", "temperature", "tools", "reasoning". */
  supported_parameters: string[];
  /** Endpoint status. 0 is active. */
  status: number;
  /** Uptime percentage over the last 15 minutes. */
  uptime_last_15m: number;
  /** Uptime percentage over the last hour. */
  uptime_last_1h: number;
  /** Uptime percentage over the last day. */
  uptime_last_1d: number;
  /** p50/p95 throughput in tokens/sec over the last hour. */
  throughput_last_1h: PercentileStats;
  /** p50/p95 time to first token in ms over the last hour. */
  latency_last_1h: PercentileStats;
  /** Whether the provider supports automatic prompt caching. */
  supports_implicit_caching: boolean;
}
