/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * AI Gateway REST API
 * Hand-authored spec for Vercel's AI Gateway REST API (https://vercel.com/docs/ai-gateway/sdks-and-apis/rest-api). Vercel does not publish a machine-readable OpenAPI/Swagger document for this API, so this file mirrors the documented REST reference and is kept in sync manually. See the `packages/ai-gateway-sdk:sync-openapi-spec` skill for the re-sync procedure. This covers only the lookup/discovery endpoints (models, credits, generation, spend reports) — sending inference requests goes through the Chat Completions, Responses, Anthropic Messages, or OpenResponses APIs, which are not modeled here.
 * OpenAPI spec version: v1
 */
import type { ModelArchitecture } from './modelArchitecture.ts';
import type { ModelEndpoint } from './modelEndpoint.ts';

export interface ModelEndpointsDetail {
  /** Model identifier. */
  id: string;
  /** Human-readable model name. */
  name: string;
  /** Unix timestamp when the model was added to AI Gateway. */
  created: number;
  /** Unix timestamp when the model was released by its creator. */
  released: number;
  /** Model description. */
  description: string;
  architecture: ModelArchitecture;
  endpoints: ModelEndpoint[];
}
