/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * AI Gateway REST API
 * Hand-authored spec for Vercel's AI Gateway REST API (https://vercel.com/docs/ai-gateway/sdks-and-apis/rest-api). Vercel does not publish a machine-readable OpenAPI/Swagger document for this API, so this file mirrors the documented REST reference and is kept in sync manually. See the `packages/ai-gateway-sdk:sync-openapi-spec` skill for the re-sync procedure. This covers only the lookup/discovery endpoints (models, credits, generation, spend reports) — sending inference requests goes through the Chat Completions, Responses, Anthropic Messages, or OpenResponses APIs, which are not modeled here.
 * OpenAPI spec version: v1
 */

/**
 * One tier of context-size-based tiered pricing.
 */
export interface PricingTier {
  /** Cost per token for this tier. */
  cost: string;
  /** Minimum token count for this tier (inclusive). */
  min: number;
  /** Maximum token count for this tier (exclusive). Omitted for the highest tier. */
  max?: number;
}
