/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * AI Gateway REST API
 * Hand-authored spec for Vercel's AI Gateway REST API (https://vercel.com/docs/ai-gateway/sdks-and-apis/rest-api). Vercel does not publish a machine-readable OpenAPI/Swagger document for this API, so this file mirrors the documented REST reference and is kept in sync manually. See the `packages/ai-gateway-sdk:sync-openapi-spec` skill for the re-sync procedure. This covers only the lookup/discovery endpoints (models, credits, generation, spend reports) — sending inference requests goes through the Chat Completions, Responses, Anthropic Messages, or OpenResponses APIs, which are not modeled here.
 * OpenAPI spec version: v1
 */

/**
 * One aggregated row. Only the grouping field matching the request's group_by is present alongside the metrics — this schema lists all possible grouping fields together for reference, but a real response row contains just one of them.
 */
export interface SpendReportRow {
  /** Present when group_by=day and date_part=day (default). The UTC date for the bucket (YYYY-MM-DD). */
  day?: string;
  /** Present when group_by=day and date_part=hour. The UTC hour for the bucket (YYYY-MM-DDTHH). */
  hour?: string;
  /** Present when group_by=user. The user ID attached to the request. */
  user?: string;
  /** Present when group_by=model. The model in creator/model-name form. */
  model?: string;
  /** Present when group_by=tag. A single tag value (one row per tag in the request). */
  tag?: string;
  /** Present when group_by=provider. The provider that served the request. */
  provider?: string;
  /** Present when group_by=credential_type. "byok" or "system". */
  credential_type?: string;
  /** Present when group_by=zero_data_retention. "true" or "false". */
  zero_data_retention?: string;
  /** Present when group_by=api_key_name. The human-readable name of the API key that served the request. */
  api_key_name?: string;
  /** Charged price in USD. Returns 0.00 for BYOK requests. */
  total_cost: number;
  /** Market price of the request at the time it ran. Includes both BYOK and non-BYOK cost. */
  market_cost: number;
  /** Surcharge portion of total_cost (e.g. from add-on capabilities). */
  surcharge_cost: number;
  /** AI Gateway's own cost, separate from the provider rate. */
  gateway_cost: number;
  /** Input tokens used. */
  input_tokens: number;
  /** Output tokens used. */
  output_tokens: number;
  /** Cached input tokens. */
  cached_input_tokens: number;
  /** Cache creation tokens. */
  cache_creation_input_tokens: number;
  /** Reasoning tokens. */
  reasoning_tokens: number;
  /** Number of requests in this row. */
  request_count: number;
}
