/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * AI Gateway REST API
 * Hand-authored spec for Vercel's AI Gateway REST API (https://vercel.com/docs/ai-gateway/sdks-and-apis/rest-api). Vercel does not publish a machine-readable OpenAPI/Swagger document for this API, so this file mirrors the documented REST reference and is kept in sync manually. See the `packages/ai-gateway-sdk:sync-openapi-spec` skill for the re-sync procedure. This covers only the lookup/discovery endpoints (models, credits, generation, spend reports) — sending inference requests goes through the Chat Completions, Responses, Anthropic Messages, or OpenResponses APIs, which are not modeled here.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


/**
 * Follows the OpenAI models API format. No authentication required.
 * @summary List all available models.
 */
export const ListModelsResponse = zod.object({
  "object": zod.string().describe('Always \"list\".'),
  "data": zod.array(zod.object({
  "id": zod.string().describe('Model identifier, e.g. \"openai\/gpt-5.5\".'),
  "object": zod.string().describe('Always \"model\".'),
  "created": zod.number().describe('Unix timestamp when the model was added to AI Gateway.'),
  "released": zod.number().describe('Unix timestamp when the model was released by its creator.'),
  "owned_by": zod.string().describe('Model provider or owner.'),
  "name": zod.string().describe('Human-readable model name.'),
  "description": zod.string().describe('Model description.'),
  "context_window": zod.number().describe('Maximum context length in tokens.'),
  "max_tokens": zod.number().describe('Maximum output tokens.'),
  "type": zod.enum(['language', 'embedding', 'reranking', 'image', 'video']),
  "tags": zod.array(zod.string()).describe('Capability tags, e.g. \"reasoning\", \"tool-use\", \"vision\", \"file-input\".'),
  "pricing": zod.object({
  "input": zod.string().optional().describe('Base cost per input token.'),
  "input_tiers": zod.array(zod.object({
  "cost": zod.string().describe('Cost per token for this tier.'),
  "min": zod.number().describe('Minimum token count for this tier (inclusive).'),
  "max": zod.number().optional().describe('Maximum token count for this tier (exclusive). Omitted for the highest tier.')
}).describe('One tier of context-size-based tiered pricing.')).optional().describe('Tiered pricing for input tokens, when applicable.'),
  "output": zod.string().optional().describe('Base cost per output token (language models only).'),
  "output_tiers": zod.array(zod.object({
  "cost": zod.string().describe('Cost per token for this tier.'),
  "min": zod.number().describe('Minimum token count for this tier (inclusive).'),
  "max": zod.number().optional().describe('Maximum token count for this tier (exclusive). Omitted for the highest tier.')
}).describe('One tier of context-size-based tiered pricing.')).optional().describe('Tiered pricing for output tokens, when applicable.'),
  "input_cache_read": zod.string().optional().describe('Cost per cached input token (read).'),
  "input_cache_write": zod.string().optional().describe('Cost per input token (cache write).'),
  "image": zod.string().optional().describe('Cost per generated image (image models only).'),
  "web_search": zod.string().optional().describe('Cost per web search request.')
}).describe('Pricing information. Structure varies by model type — most fields are optional and only present for the relevant model type.')
}))
})


/**
 * Returns per-endpoint pricing, capabilities, uptime, and throughput for every provider serving the given model. No authentication required.
 * @summary Get every provider endpoint serving a model.
 */
export const GetModelEndpointsParams = zod.object({
  "creator": zod.string().describe('The model creator\/owner segment of the model id, e.g. \"google\" in \"google\/gemini-3.1-pro-preview\".'),
  "model": zod.string().describe('The model name segment of the model id, e.g. \"gemini-3.1-pro-preview\" in \"google\/gemini-3.1-pro-preview\".')
})

export const GetModelEndpointsResponse = zod.object({
  "data": zod.object({
  "id": zod.string().describe('Model identifier.'),
  "name": zod.string().describe('Human-readable model name.'),
  "created": zod.number().describe('Unix timestamp when the model was added to AI Gateway.'),
  "released": zod.number().describe('Unix timestamp when the model was released by its creator.'),
  "description": zod.string().describe('Model description.'),
  "architecture": zod.object({
  "tokenizer": zod.string().nullable().describe('Tokenizer name, when known.'),
  "instruct_type": zod.string().nullable().describe('Instruction-tuning format, when known.'),
  "modality": zod.string().describe('Input\/output modality string, e.g. \"text+image+file→text\".'),
  "input_modalities": zod.array(zod.string()).describe('Supported input types, e.g. \"text\", \"image\", \"file\".'),
  "output_modalities": zod.array(zod.string()).describe('Supported output types, e.g. \"text\".')
}),
  "endpoints": zod.array(zod.object({
  "name": zod.string().describe('Endpoint display name, e.g. \"google | google\/gemini-3.1-pro-preview\".'),
  "model_name": zod.string().describe('Human-readable model name.'),
  "context_length": zod.number().describe('Maximum context window in tokens for this endpoint.'),
  "pricing": zod.object({
  "prompt": zod.string().describe('Cost per prompt token.'),
  "completion": zod.string().describe('Cost per completion token.'),
  "input_cache_read": zod.string().optional().describe('Cost per cached input token (read).'),
  "input_cache_write": zod.string().optional().describe('Cost per input token (cache write).')
}),
  "provider_name": zod.string().describe('Provider name, e.g. \"google\", \"anthropic\".'),
  "max_completion_tokens": zod.number().describe('Maximum output tokens for this endpoint.'),
  "supported_parameters": zod.array(zod.string()).describe('API parameters supported by this endpoint, e.g. \"max_tokens\", \"temperature\", \"tools\", \"reasoning\".'),
  "status": zod.number().describe('Endpoint status. 0 is active.'),
  "uptime_last_15m": zod.number().describe('Uptime percentage over the last 15 minutes.'),
  "uptime_last_1h": zod.number().describe('Uptime percentage over the last hour.'),
  "uptime_last_1d": zod.number().describe('Uptime percentage over the last day.'),
  "throughput_last_1h": zod.object({
  "p50": zod.number().describe('50th percentile value.'),
  "p95": zod.number().describe('95th percentile value.')
}).describe('p50\/p95 throughput in tokens\/sec over the last hour.'),
  "latency_last_1h": zod.object({
  "p50": zod.number().describe('50th percentile value.'),
  "p95": zod.number().describe('95th percentile value.')
}).describe('p50\/p95 time to first token in ms over the last hour.'),
  "supports_implicit_caching": zod.boolean().describe('Whether the provider supports automatic prompt caching.')
}).describe('One provider\'s endpoint serving a model.'))
})
})


/**
 * Returns the team's current AI Gateway Credits balance and lifetime spend. The team is inferred from the API key or Vercel OIDC token.
 * @summary Check the team's AI Gateway Credits balance and total spend.
 */
export const GetCreditsResponse = zod.object({
  "balance": zod.string().describe('Remaining credit balance, in USD.'),
  "total_used": zod.string().describe('Total credits used to date, in USD.')
})


/**
 * Generation information becomes available shortly after the generation completes. Much of this data is also returned in `providerMetadata` on the chat completion response. Generation IDs are returned as the `id` field on every chat completion response, and injected into the first content chunk on streaming responses so you can capture them before the stream completes.
 * @summary Look up cost, latency, and token usage for a specific generation.
 */
export const GetGenerationQueryParams = zod.object({
  "id": zod.string().describe('The generation ID to look up. Format: gen_<ulid>.')
})

export const GetGenerationResponse = zod.object({
  "data": zod.object({
  "id": zod.string().describe('The generation ID.'),
  "total_cost": zod.number().describe('Total cost in USD for this generation, including any surcharges (e.g. Zero Data Retention or Custom Reporting writes).'),
  "upstream_inference_cost": zod.number().describe('Market price the provider would have charged for the inference. Non-zero only for BYOK generations, where total_cost does not include this amount; 0 otherwise.'),
  "usage": zod.number().describe('Same as total_cost. Kept for compatibility with the OpenRouter schema this endpoint mirrors.'),
  "created_at": zod.iso.datetime({"offset":true}).describe('ISO 8601 timestamp when the generation was created.'),
  "model": zod.string().describe('Model identifier used for this generation.'),
  "is_byok": zod.boolean().describe('Whether this generation used Bring Your Own Key (BYOK) credentials.'),
  "provider_name": zod.string().describe('The provider that served this generation.'),
  "streamed": zod.boolean().describe('Whether this generation used streaming.'),
  "finish_reason": zod.string().describe('Why the generation ended, e.g. \"stop\", \"length\", \"content_filter\", \"tool_calls\".'),
  "latency": zod.number().describe('Time to first token in milliseconds.'),
  "generation_time": zod.number().describe('Total generation time in milliseconds.'),
  "tokens_prompt": zod.number().describe('Number of prompt tokens.'),
  "tokens_completion": zod.number().describe('Number of completion tokens.'),
  "native_tokens_prompt": zod.number().describe('Native prompt tokens (provider-specific).'),
  "native_tokens_completion": zod.number().describe('Native completion tokens (provider-specific).'),
  "native_tokens_reasoning": zod.number().describe('Reasoning tokens used.'),
  "native_tokens_cached": zod.number().describe('Cached input tokens read.'),
  "native_tokens_cache_creation": zod.number().describe('Cache creation tokens written.'),
  "billable_web_search_calls": zod.number().describe('Number of billable web search calls performed during this generation.')
})
})


/**
 * Returns aggregated spend over a date range. The team is inferred from the API key or OIDC token. Available on Pro and Enterprise plans only — Hobby and Pro-trial plans cannot use this endpoint. Custom Reporting is billed per query; see https://vercel.com/docs/ai-gateway/observability-and-spend/custom-reporting for pricing. It can take a few minutes for requests to appear in this endpoint. Each row contains only the single grouping field that matches `group_by`, plus the aggregated metrics.
 * @summary Query aggregated spend reports for the team.
 */
export const GetSpendReportQueryParams = zod.object({
  "start_date": zod.iso.date().describe('Start date in YYYY-MM-DD format, inclusive, UTC.'),
  "end_date": zod.iso.date().describe('End date in YYYY-MM-DD format, inclusive, UTC.'),
  "group_by": zod.enum(['day', 'user', 'model', 'tag', 'provider', 'credential_type', 'zero_data_retention', 'api_key_name']).optional().describe('How to aggregate results. Each row represents one bucket of this dimension.'),
  "date_part": zod.enum(['day', 'hour']).optional().describe('Time granularity. Only applies when group_by=day. Use \"hour\" for per-hour rows, \"day\" for per-day rows.'),
  "user_id": zod.string().optional().describe('Filter by a specific user ID.'),
  "model": zod.string().optional().describe('Filter by a specific model in creator\/model-name format.'),
  "provider": zod.string().optional().describe('Filter by provider.'),
  "credential_type": zod.enum(['byok', 'system']).optional().describe('Filter by credential type.'),
  "zero_data_retention": zod.boolean().optional().describe('Filter to Zero Data Retention (ZDR)-requested vs non-ZDR requests.'),
  "tags": zod.string().optional().describe('Filter by one or more comma-separated tags. By default, requests match when they contain any listed tag.'),
  "tags_match": zod.enum(['any', 'all']).optional().describe('Match mode for `tags`. Use \"any\" to match requests with any listed tag, or \"all\" to require every listed tag.')
})

export const GetSpendReportResponse = zod.object({
  "results": zod.array(zod.object({
  "day": zod.string().optional().describe('Present when group_by=day and date_part=day (default). The UTC date for the bucket (YYYY-MM-DD).'),
  "hour": zod.string().optional().describe('Present when group_by=day and date_part=hour. The UTC hour for the bucket (YYYY-MM-DDTHH).'),
  "user": zod.string().optional().describe('Present when group_by=user. The user ID attached to the request.'),
  "model": zod.string().optional().describe('Present when group_by=model. The model in creator\/model-name form.'),
  "tag": zod.string().optional().describe('Present when group_by=tag. A single tag value (one row per tag in the request).'),
  "provider": zod.string().optional().describe('Present when group_by=provider. The provider that served the request.'),
  "credential_type": zod.string().optional().describe('Present when group_by=credential_type. \"byok\" or \"system\".'),
  "zero_data_retention": zod.string().optional().describe('Present when group_by=zero_data_retention. \"true\" or \"false\".'),
  "api_key_name": zod.string().optional().describe('Present when group_by=api_key_name. The human-readable name of the API key that served the request.'),
  "total_cost": zod.number().describe('Charged price in USD. Returns 0.00 for BYOK requests.'),
  "market_cost": zod.number().describe('Market price of the request at the time it ran. Includes both BYOK and non-BYOK cost.'),
  "surcharge_cost": zod.number().describe('Surcharge portion of total_cost (e.g. from add-on capabilities).'),
  "gateway_cost": zod.number().describe('AI Gateway\'s own cost, separate from the provider rate.'),
  "input_tokens": zod.number().describe('Input tokens used.'),
  "output_tokens": zod.number().describe('Output tokens used.'),
  "cached_input_tokens": zod.number().describe('Cached input tokens.'),
  "cache_creation_input_tokens": zod.number().describe('Cache creation tokens.'),
  "reasoning_tokens": zod.number().describe('Reasoning tokens.'),
  "request_count": zod.number().describe('Number of requests in this row.')
}).describe('One aggregated row. Only the grouping field matching the request\'s group_by is present alongside the metrics — this schema lists all possible grouping fields together for reference, but a real response row contains just one of them.'))
})


